In [30]:
import matplotlib.pyplot as plt          
import seaborn as sns
import numpy as np
import pandas as pd
print('lib import completed')

lib import completed


In [31]:
data= pd.read_csv('Concrete_Data - copy.csv')
X = data.iloc[:,[0,1,2,3,4,5,6]].values                  #independent values
y = data.iloc[:, 7].values                               #dependent values
data

Cement  (component 1)(kg in a m^3 mixture)  \
0                                          540.0   
1                                          540.0   
2                                          332.5   
3                                          332.5   
4                                          198.6   
...                                          ...   
1025                                       276.4   
1026                                       322.2   
1027                                       148.5   
1028                                       159.1   
1029                                       260.9   

      Blast Furnace Slag (component 2)(kg in a m^3 mixture)  \
0                                                   0.0       
1                                                   0.0       
2                                                 142.5       
3                                                 142.5       
4                                                 132.4       
...                                                 ...       
1025                                              116.0       
1026                                                0.0       
1027                                              139.4       
1028                                              186.7       
1029                                              100.5       

      Fly Ash (component 3)(kg in a m^3 mixture)  \
0                                            0.0   
1                                            0.0   
2                                            0.0   
3                                            0.0   
4                                            0.0   
...                                          ...   
1025                                        90.3   
1026                                       115.6   
1027                                       108.6   
1028                                         0.0   
1029                                        78.3   

      Water  (component 4)(kg in a m^3 mixture)  \
0                                         162.0   
1                                         162.0   
2                                         228.0   
3                                         228.0   
4                                         192.0   
...                                         ...   
1025                                      179.6   
1026                                      196.0   
1027                                      192.7   
1028                                      175.6   
1029                                      200.6   

      Superplasticizer (component 5)(kg in a m^3 mixture)  \
0                                                   2.5     
1                                                   2.5     
2                                                   0.0     
3                                                   0.0     
4                                                   0.0     
...                                                 ...     
1025                                                8.9     
1026                                               10.4     
1027                                                6.1     
1028                                               11.3     
1029                                                8.6     

      Coarse Aggregate  (component 6)(kg in a m^3 mixture)  \
0                                                1040.0      
1                                                1055.0      
2                                                 932.0      
3                                                 932.0      
4                                                 978.4      
...                                                 ...      
1025                                              870.1      
1026                                              817.9      
1027                                              892.4      
1028                             

In [32]:
X=X.astype(np.float64)
Y=y.astype(np.float64)

In [33]:
#model evalution 
from sklearn.model_selection import train_test_split
Itrain,Itest,Dtrain,Dtest= train_test_split(X, Y, test_size = 0.2, random_state = 0)

In [34]:
from sklearn.linear_model import LinearRegression            #importing Linear Regression
LR=LinearRegression()
LR.fit(Itrain,Dtrain)

LinearRegression()

In [35]:
#prediction of test data
Yprediction=LR.predict(Itest)

In [36]:
import statsmodels.formula.api as sm                            #Importing ststsmodel
import statsmodels.regression.linear_model as SM

In [37]:
I=np.append(arr=np.ones([1030,5]).astype(int),values=X,axis=1)               #appending input values 
print(I)

[[1.000e+00 1.000e+00 1.000e+00 ... 2.500e+00 1.040e+03 6.760e+02]
 [1.000e+00 1.000e+00 1.000e+00 ... 2.500e+00 1.055e+03 6.760e+02]
 [1.000e+00 1.000e+00 1.000e+00 ... 0.000e+00 9.320e+02 5.940e+02]
 ...
 [1.000e+00 1.000e+00 1.000e+00 ... 6.100e+00 8.924e+02 7.800e+02]
 [1.000e+00 1.000e+00 1.000e+00 ... 1.130e+01 9.896e+02 7.889e+02]
 [1.000e+00 1.000e+00 1.000e+00 ... 8.600e+00 8.645e+02 7.615e+02]]


In [38]:
#endog-dependent
#exdog-independent
Iopt=I[:,[0,1,2,3,4,5,6]]
Optimizer=SM.OLS(endog=Y,exog=Iopt).fit()                              #OLS = ordinary least squares
Optimizer.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.007
Model:                            OLS   Adj. R-squared:                  0.005
Method:                 Least Squares   F-statistic:                     3.737
Date:                Sat, 18 Sep 2021   Prob (F-statistic):             0.0242
Time:                        00:37:03   Log-Likelihood:                -5727.5
No. Observations:                1030   AIC:                         1.146e+04
Df Residuals:                    1027   BIC:                         1.148e+04
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          6.8205      1.303      5.236      0.000       4.264       9.377
x1             6.8205      1.303      5.236      0.000       4.264       9.377
x2             6.8205      1.303      5.236      0.000       4.264       9.377
x3             6.8205      1.303      5.236      0.000       4.264       9.377
x4             6.8205      1.303      5.236      0.000       4.264       9.377
x5             0.0456      0.020      2.334      0.020       0.007       0.084
x6            -0.0172      0.024     -0.726      0.468      -0.064       0.029
==============================================================================
Omnibus:                      719.973   Durbin-Watson:                   1.109
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             7938.017
Skew:                           3.221   Prob(JB):                         0.00
Kurtosis:                      14.977   Cond. No.                     2.90e+19
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 1.15e-31. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.
"""

In [39]:
#endog-dependent
#exdog-independent
Iopt=I[:,[0,1,2,3]]                           #just taking most significant values.
Optimizer=SM.OLS(endog=Y,exog=Iopt).fit()
Optimizer.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.000
Model:                            OLS   Adj. R-squared:                  0.000
Method:                 Least Squares   F-statistic:                       nan
Date:                Sat, 18 Sep 2021   Prob (F-statistic):                nan
Time:                        00:37:07   Log-Likelihood:                -5731.2
No. Observations:                1030   AIC:                         1.146e+04
Df Residuals:                    1029   BIC:                         1.147e+04
Df Model:                           0                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const         11.4155      0.492     23.199      0.000      10.450      12.381
x1            11.4155      0.492     23.199      0.000      10.450      12.381
x2            11.4155      0.492     23.199      0.000      10.450      12.381
x3            11.4155      0.492     23.199      0.000      10.450      12.381
==============================================================================
Omnibus:                      727.479   Durbin-Watson:                   1.101
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             8117.117
Skew:                           3.264   Prob(JB):                         0.00
Kurtosis:                      15.104   Cond. No.                     5.31e+47
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 1.46e-92. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.
"""