In [2]:
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import pandas as pd
print('lib import completed')

lib import completed


In [3]:
data= pd.read_csv('FuelConsumption.csv')
X = data.iloc[:,[0,4,5,8,9,10]].values
#independent
y = data.iloc[:, 12].values
#dependent
data

MODELYEAR   MAKE       MODEL    VEHICLECLASS  ENGINESIZE  CYLINDERS  \
0          2014  ACURA         ILX         COMPACT         2.0          4   
1          2014  ACURA         ILX         COMPACT         2.4          4   
2          2014  ACURA  ILX HYBRID         COMPACT         1.5          4   
3          2014  ACURA     MDX 4WD     SUV - SMALL         3.5          6   
4          2014  ACURA     RDX AWD     SUV - SMALL         3.5          6   
...         ...    ...         ...             ...         ...        ...   
1062       2014  VOLVO    XC60 AWD     SUV - SMALL         3.0          6   
1063       2014  VOLVO    XC60 AWD     SUV - SMALL         3.2          6   
1064       2014  VOLVO    XC70 AWD     SUV - SMALL         3.0          6   
1065       2014  VOLVO    XC70 AWD     SUV - SMALL         3.2          6   
1066       2014  VOLVO    XC90 AWD  SUV - STANDARD         3.2          6   

     TRANSMISSION FUELTYPE  FUELCONSUMPTION_CITY  FUELCONSUMPTION_HWY  \
0             AS5        Z                   9.9                  6.7   
1              M6        Z                  11.2                  7.7   
2             AV7        Z                   6.0                  5.8   
3             AS6        Z                  12.7                  9.1   
4             AS6        Z                  12.1                  8.7   
...           ...      ...                   ...                  ...   
1062          AS6        X                  13.4                  9.8   
1063          AS6        X                  13.2                  9.5   
1064          AS6        X                  13.4                  9.8   
1065          AS6        X                  12.9                  9.3   
1066          AS6        X                  14.9                 10.2   

      FUELCONSUMPTION_COMB  FUELCONSUMPTION_COMB_MPG  CO2EMISSIONS  
0                      8.5                        33           196  
1                      9.6                        29           221  
2                      5.9                        48           136  
3                     11.1                        25           255  
4                     10.6                        27           244  
...                    ...                       ...           ...  
1062                  11.8                        24           271  
1063                  11.5                        25           264  
1064                  11.8                        24           271  
1065                  11.3                        25           260  
1066                  12.8                        22           294  

[1067 rows x 13 columns]

In [6]:
X=X.astype(np.float64)
Y=y.astype(np.float64)

......................................

In [7]:
#model evalution
from sklearn.model_selection import train_test_split
Itrain,Itest,Dtrain,Dtest= train_test_split(X, Y, test_size = 0.2, random_state = 0)

In [8]:
from sklearn.linear_model import LinearRegression
LR=LinearRegression()
LR.fit(Itrain,Dtrain)

LinearRegression()

In [9]:
#prediction of test data
Yprediction=LR.predict(Itest)

..........................................

In [10]:
import statsmodels.formula.api as sm
import statsmodels.regression.linear_model as SM

In [11]:
I=np.append(arr=np.ones([1067,5]).astype(int),values=X,axis=1)
print(I)

[[ 1.   1.   1.  ...  9.9  6.7  8.5]
 [ 1.   1.   1.  ... 11.2  7.7  9.6]
 [ 1.   1.   1.  ...  6.   5.8  5.9]
 ...
 [ 1.   1.   1.  ... 13.4  9.8 11.8]
 [ 1.   1.   1.  ... 12.9  9.3 11.3]
 [ 1.   1.   1.  ... 14.9 10.2 12.8]]


In [12]:
#endog-dependent
#exdog-independent
Iopt=I[:,[0,4,5,8,9,10]]
Optimizer=SM.OLS(endog=Y,exog=Iopt).fit()
Optimizer.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.807
Model:                            OLS   Adj. R-squared:                  0.806
Method:                 Least Squares   F-statistic:                     1482.
Date:                Mon, 06 Sep 2021   Prob (F-statistic):               0.00
Time:                        22:52:07   Log-Likelihood:                -5062.8
No. Observations:                1067   AIC:                         1.013e+04
Df Residuals:                    1063   BIC:                         1.015e+04
Df Model:                           3                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       1.799e-05   7.45e-07     24.155      0.000    1.65e-05    1.95e-05
x1          1.799e-05   7.45e-07     24.155      0.000    1.65e-05    1.95e-05
x2             0.0362      0.002     24.155      0.000       0.033       0.039
x3             2.4728     16.389      0.151      0.880     -29.685      34.631
x4           -12.2311     13.511     -0.905      0.366     -38.742      14.280
x5            22.9902     29.814      0.771      0.441     -35.512      81.492
==============================================================================
Omnibus:                      143.386   Durbin-Watson:                   2.187
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              249.523
Skew:                          -0.858   Prob(JB):                     6.56e-55
Kurtosis:                       4.632   Cond. No.                     6.64e+19
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 9.83e-31. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.
"""

In [13]:
Iopt=I[:,[0,4,5]]
Optimizer=SM.OLS(endog=Y,exog=Iopt).fit()
Optimizer.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.000
Model:                            OLS   Adj. R-squared:                  0.000
Method:                 Least Squares   F-statistic:                       nan
Date:                Mon, 06 Sep 2021   Prob (F-statistic):                nan
Time:                        22:52:13   Log-Likelihood:                -5940.5
No. Observations:                1067   AIC:                         1.188e+04
Df Residuals:                    1066   BIC:                         1.189e+04
Df Model:                           0                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       6.317e-05   4.78e-07    132.072      0.000    6.22e-05    6.41e-05
x1          6.317e-05   4.78e-07    132.072      0.000    6.22e-05    6.41e-05
x2             0.1272      0.001    132.072      0.000       0.125       0.129
==============================================================================
Omnibus:                       43.711   Durbin-Watson:                   0.612
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               48.446
Skew:                           0.519   Prob(JB):                     3.02e-11
Kurtosis:                       2.885   Cond. No.                     2.20e+35
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 8.94e-62. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.
"""

In [ ]:
....................................