In [1]:
import lib
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
print('ibraries imported')

ibraries imported


In [3]:
Sdata=pd.read_csv('Iris.csv')
#%% input and out data
In=Sdata.iloc[:,1:5].values
Dp=Sdata.iloc[:,5].values

In [4]:
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
L=LabelEncoder()
Sdata['Species']=L.fit_transform(Sdata['Species'])
Sdata['Species'].unique()

array([0, 1, 2])

In [6]:
std=StandardScaler() # object creation
In=std.fit_transform(In)

In [7]:
#%% training and test split
Intrain, Intest, Dptrain, Dptest=train_test_split(In, Dp,test_size=0.20,random_state=0)

In [8]:
#%% Apply KNN choosen classifier, create object apply fit method
from sklearn.neighbors import KNeighborsClassifier
KNN=KNeighborsClassifier(n_neighbors=2,metric='minkowski',p=2)
KNN.fit(Intrain, Dptrain)

KNeighborsClassifier(n_neighbors=2)

In [9]:
#%% apply the predict
Dp_Predicted=KNN.predict(Intest)
#%% apply Confusion Matrix to calculate  accuracy
from sklearn.metrics import confusion_matrix
result=confusion_matrix(Dptest,Dp_Predicted)
print(result)

[[11  0  0]
 [ 0 13  0]
 [ 0  1  5]]
